### ISSUE TITLE
Please add compilation instructions

### ISSUE THREAD

**Issue by DanyGee** [FelixdelasPozas/WhirlWindWarp#2]
Please add compilation instructions.
Currently I get:
```
CMake Warning at CMakeLists.txt:23 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


CMake Error at CMakeLists.txt:51 (qt5_add_resources):
  Unknown CMake command "qt5_add_resources".
```

**Comment by DanyGee** [comment]
Added the following to CMakeLists.txt:

```
# Set Prefix Path
set (CMAKE_PREFIX_PATH "C:\\Qt\\Qt5.12.12\\5.12.12\\mingw73_64\\")
```

...and solved the previous problem, but got blessed with another one:

`:-1: error: D8021: invalid numeric argument '/Wno-deprecated' [C:\Users\*********\Downloads\WhirlWindWarp-master\build\WhirlWindWarp.vcxproj]`

**Comment by FelixdelasPozas** [comment]
Hi @DanyGee.

The compilation is very straightforward when using CMake. The only dependency is Qt5 (for now, I will use native windows and OpenGL in the future removing the need of Qt5 but I didn't have the time to do it).

As explained in the readme (Compilation requirements) the specified compiler is Mingw (gcc for Windows), if you're using Visual Studio you'll find that the CMAKE_CXX_FLAGS (line 27 in CMakeLists.txt) will produce errors as **those are gcc parameters**. Just **comment the line 27** of CMakeLists.txt with a **#** character and configure again. The default Visual Studio compiler parameters will be used. 

You shouldn't have more problems, as the only dependency is Qt5 and is a very simple project. 

Regards, 
Félix.

Edited: If you use Cmake-gui on Windows to configure the project when CMake asks for the location of Qt5 libraries just enter the path of  **< your Qt installation path >\lib\cmake\\< Qt library name>** . So if Qt5_Widgets is required just put **< your Qt installation path >\lib\cmake\Qt5Widgets**.

**Comment by DanyGee** [comment]
The main problem is, I am not experienced in programming 😞 
Commenting the line results in even more problems...
![image](https://user-images.githubusercontent.com/26818551/153199930-e8d8eab8-06f3-4153-a901-a8f2b2a54068.png)

Please advise.

If possible, we can do a screensharing session on Discord or Telegram to quickly solve the problem.

**Comment by FelixdelasPozas** [comment]
First change the line ```set (CMAKE_PREFIX_PATH "C:\\Qt\\Qt5.12.12\\5.12.12\\mingw73_64\\")``` with ```list(APPEND CMAKE_PREFIX_PATH "C:\\Qt\\Qt5.12.12\\5.12.12\\mingw73_64\\")``` as CMAKE_PREFIX_PATH is a list of directories so if you use SET you're removing the other directories in the variable. 

By your screenshots it seems that compilation goes well but the linking phase fails with numerous errors. All errors look to be related to Qt libraries so, after making the CMAKE_PREFIX_PATH change, run cmake again and make sure all the related Qt libraries have correct paths. 
Mine looks like this: 
![Clipboard01](https://user-images.githubusercontent.com/12167134/153220350-1b0318c4-4498-424e-995d-d51e84a6bc87.png)

All 4 **Qt_DIR** variables must point to the correct lib\cmake subdirectories where you have Qt installed. 

Then try again the compilation process with Visual Studio.

**Comment by DanyGee** [comment]
Same happens.
Maybe I have the env not properly prepared.
When is the best time for you for a screensharing session?
It will be the fastest way of troubleshooting.

Are they not pointing to the right ones?
![image](https://user-images.githubusercontent.com/26818551/153354828-6a37039e-9a48-4059-ad0f-e326659b9546.png)

**Comment by FelixdelasPozas** [comment]
It seems that you're using the Mingw libraries with Visual Studio and that seems to be the problem in the linking phase. You'll need to use the libraries that match your compiler. If I remember correctly (nowadays I compile Qt instead of downloading them) in the installer it asks for the version you want to install, like in this screenshot:
![M6dOkc](https://user-images.githubusercontent.com/12167134/153358221-edecd988-1112-4b97-9057-6d5a59d65246.png)
It's for another version but it should be the same for the one you downloaded. Choose the MSVC version closer to the one you have (even if its not 2022 version) it should work because is a "format" problem, Visual Studio dll and Mingw dll are a bit different. Mingw can link with VS with a little extra work but VS can't link with Mingw dlls).

You'll need to install the ones for the Visual Studio version you're using and then start the process again. Empty your "build" directory and run CMake again and when it asks for the Qt5 libraries use the Visual Studio version. 
The rest I've seen from your screenshot seems to be ok. If this doesn't work maybe we can do a TeamViewer or something similar on the weekend (sorry, it's much more difficult for me to do it during the rest of the week).

**Comment by DanyGee** [comment]
Did as you explained.
It built, but throws yet another 3 errors while launching the screensaver:
![image](https://user-images.githubusercontent.com/26818551/153364893-39cde4fc-7366-4feb-b741-5e2800e6ccec.png)
![image](https://user-images.githubusercontent.com/26818551/153364509-6c50c9d5-4e9c-4b85-a184-4e0bd1e4e127.png)
![image](https://user-images.githubusercontent.com/26818551/153364551-7a458dc2-7efa-4156-823a-83045ef1ed2c.png)
What is totally strange, why there is an additional "d" in all the names of the dll's? 🤯 

P.S. Teamviewer is also perfectly fine for me.

**Comment by FelixdelasPozas** [comment]
Now it seems to compile and link correctly (we're almost there!). Those errors are because the screensaver cannot find the dlls when executing. The "d" are the "debug" versions of the dlls. I've seen you're compiling all versions in CMake with variable  ```CMAKE_CONFIGURATION_TYPES ``` with **Release, Debug, MinimumSize and ReleaseWithDebugInfo.** You could/must change that variable to just **Release** as it will produce the faster executable (without the debug information that you don't need). 

Then to solve the execution problems locate the dlls and copy them to the directory where the screensaver is. If you want to test the screensaver right as you have it right now (without doing anything else) just copy Qt5Widgetsd.dll, Qt5Cored.dll and Qt5Guid.dll where the scr file is. Then it will launch correctly.  And if you compile the screensaver in Release the dlls to copy are Qt5Widgets.dll, Qt5Core.dll and Qt5Gui.dll (those are the Release versions of the dlls).

**Comment by DanyGee** [comment]
As you wrote, almost there...

![image](https://user-images.githubusercontent.com/26818551/153371453-78230a9c-10ca-4608-8924-6e851c2651af.png)

![image](https://user-images.githubusercontent.com/26818551/153369581-b98d33ce-a66a-4fb4-b5bc-02419f308842.png)
Once I hit OK program ends, meanwhile it does nothing.

**Comment by FelixdelasPozas** [comment]
Those are the default parameters for screensavers in Windows (those are mandatory to work) https://docs.microsoft.com/en-us/troubleshoot/windows/win32/screen-saver-command-line .
Use the explorer to go where the scr file is and select it with your mouse and hit the right button. The context menu will have the "Test", "Configure" and "Install" options.
![Clipboard01](https://user-images.githubusercontent.com/12167134/153372229-7bfb3bc7-2e66-467c-ac55-98fe325588c5.png)

If you want the screensaver to be in the list of available screensavers you'll need to copy the following files to **C:\\Windows\\**
WhirlWindWarp.scr, Qt5Core.dll, Qt5Widgets.dll and Qt5Gui.dll (I think the "Install" option will copy only the scr).
With the "Test" option you'll be able to see it in action. I don't know if you'll be disappointed because it's a very old Linux screensaver :disappointed: 

Edit: In my computer if I double-click the scr (that I already have in C:\Windows\) it just executes.
![Clipboard01](https://user-images.githubusercontent.com/12167134/153375532-5a9b7fd1-3f6f-481a-b633-2b0173727cd3.png)

**Comment by DanyGee** [comment]
This is exactly why I want it in Windows - to me its the best Linux screensaver ever. I use it on all my Linux Distros.
I was looking for it on Windows and found your project.
But as you can see, since yesterday I cannot get it to work 😢 

Installed it, launched it, and still not working 🤯 
(Although you can clearly see its installed, still only one instance of the file exists and only in the release folder) 🤯 
![image](https://user-images.githubusercontent.com/26818551/153375262-26894556-0b0c-4d7e-8d31-579641a49bbf.png)

**Comment by DanyGee** [comment]
How about you send me your *scr file + your needed dll's and I'll check the outcome?
I'm on Windows 11 BTW.

**Comment by FelixdelasPozas** [comment]
Yes, I was looking if there were some changes in scr for Windows 11 (that I don't have). Anyway I've uploaded my files to a [release](https://github.com/FelixdelasPozas/WhirlWindWarp/releases/tag/1.0.0) and included the svg and windows platform dlls in case those were the problem. 
Try it and tell me if it solves your problems.

Regards, 
Félix.

> to me its the best Linux screensaver ever.

Indeed :smile:

**Comment by DanyGee** [comment]
Another chapter in the "Book of Errors"...

![explorer_fsBqgkgkma](https://user-images.githubusercontent.com/26818551/153380130-c414348b-3e11-4f96-ab1a-2fe5e4a50085.png)

**Comment by FelixdelasPozas** [comment]
Create a subdirectory with the name **platforms** and move the qwindows.dll there and try again.

Edit: I've updated the release zip. Qt is somewhat *picky* with dependencies, that's why I planned to remove Qt and use OpenGL in the future to have just a scr file.

**Comment by DanyGee** [comment]
FINALLY ITS WORKING 🥳 
![image](https://user-images.githubusercontent.com/26818551/153381432-14773d90-15f3-4785-8428-0cc1130f79ec.png)
Man, THANK YOU for this project and for you patience in helping me to make this work! 🙏🏻
Hope you will find the time and a way to make using it on Windows as simple as possible 🏆

**Comment by FelixdelasPozas** [comment]
Glad to hear! Thanks to you! And my sincere apologies for making you download and install visual studio and Qt :pray: Really really sorry! 
> Hope you will find the time and a way to make using it on Windows as simple as possible

Yes, I planned to do precisely that but... :disappointed:
